""" PANEL NUMBERS AND PANEL PROPERTIES

Need to test whether having these in this file will affect the trend analysis
script
"""
import ad_config

# THINGS THAT DON't NEED TO BE IN THE PANEL CONFIG:
# Move congenica congenica_IR_template logic into upload and setoff script,
# using congenica_credentials flags
# Same for masked_reference, using lrpcr panel_name

MOKAPIPE_HAPLOTYPE_CALLER_PADDING = 0
FH_PRS_BEDFILE = "Pan4909.bed"  # Mokapipe FH_PRS BED file
MASKED_REFERENCE = f"{ad_config.TOOLS_PROJECT}:file-GF84GF00QfBfzV35Gf8Qg53q"

# "congenica_project"- None = no upload. False = SFTP upload. Number = normal
# upload
# "congenica_credentials" - "Viapath" OR "STG"
# "capture type" - Amplicon or Hybridisation
# 'sambamba_bedfile' - bedfile filename, or None
# 'variant_calling_bedfile' - bedfile filename, or None
# 'RPKM_bedfile_pan_number' - pan number, or None
# 'peddy' - true or false
# 'hsmetrics_bedfile' - bedfile filename, or None
# 'congenica_IR_template' - priority, non-priority, or None
# 'masked_reference' - false or projectid:fileid. Currently set as
# hs37d5_Pan4967.bwa-index.tar.gz

# MokaSNP does not have R numbers as it is an identity check for the GMS SMS
# Panels for WES (analysed in Congenica), SWIFT and TSO500 (analysed in QCII),
# and ArcherDX (analysed in Archer software), are applied at the point of
# analysis, so R and M numbers for these are not listed below. These pan
# numbers do not necessarily refer to bed files but rather project
# configuration (e.g. DNAnexus instances, project layout etc.)

# If the tso pan numbers, stg pan numbers or custom panels whole capture pan
# numbers change, these must be updated in the duty_csv_inputs config

# TODO use **dict.fromkeys( to reduce duplication between configuration
PANEL_DICT = {
    "Pan4009": {  # MokaSNP
        "panel_name": "mokasnp",
        "pipeline": "mokasnp",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "variant_calling_bedfile": "Pan4009.bed",
        "congenica_project": False,
        "congenica_credentials": False,
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "sambamba_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "hsmetrics_bedfile": None,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan2835": {  # TWIST WES (Viapath)
        "panel_name": "wes",
        "pipeline": "mokawes",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 20,
        "hsmetrics_bedfile": "Twist_Exome_RefSeq_CCDS_v1.2_targets.bed",
        "sambamba_bedfile": "Pan493dataSambamba.bed",
        "peddy": True,
        "congenica_project": None,
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "variant_calling_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4940": {  # TWIST WES for EB lab (Viapath)
        "panel_name": "wes_eb",
        "pipeline": "mokawes",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 20,
        "hsmetrics_bedfile": "Twist_Exome_RefSeq_CCDS_v1.2_targets.bed",
        "sambamba_bedfile": "Pan493dataSambamba.bed",
        "peddy": True,
        "congenica_project": "4697",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "variant_calling_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4081": {  # SWIFT EGFR (Viapath)
        "panel_name": "swift_egfr",
        "pipeline": "mokaamp",
        "capture_type": "Amplicon",
        "clinical_coverage_depth": 600,  # Only found in mokamp command
        "multiqc_coverage_level": 100,
        "hsmetrics_bedfile": "Pan4081.bed",
        "sambamba_bedfile": "Pan4081Sambamba.bed",
        "congenica_project": False,
        "congenica_credentials": None,
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "variant_calling_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "congenica_IR_template": None,
        "polyedge": False,
    },
    "Pan4082": {  # SWIFT 57G (Viapath)
        "panel_name": "swift_57g",
        "pipeline": "mokaamp",
        "capture_type": "Amplicon",
        "clinical_coverage_depth": 600,  # Only found in mokamp command
        "multiqc_coverage_level": 100,
        "hsmetrics_bedfile": "Pan4082.bed",
        "sambamba_bedfile": "Pan4082Sambamba.bed",
        "congenica_project": False,
        "congenica_credentials": None,
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "variant_calling_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "congenica_IR_template": None,
        "polyedge": False,
    },
    **dict.fromkeys(
        [
            "Pan4396",  # ArcherDx (Synnovis)
            "Pan5113",  # ArcherDx (BSPS)
            "Pan5115",  # ArcherDx (Control)
        ],
        {
            "panel_name": "archerdx",
            "pipeline": "archerdx",
            "capture_type": "Hybridisation",
            "clinical_coverage_depth": False,
            "multiqc_coverage_level": None,  # As we don't align for Archer
            "congenica_project": False,
            "congenica_credentials": False,
            "FH": False,
            "drylab_dnanexus_id": None,
            "masked_reference": False,
            "sambamba_bedfile": None,
            "variant_calling_bedfile": None,
            "RPKM_bedfile_pan_number": None,
            "peddy": False,
            "hsmetrics_bedfile": None,
            "congenica_IR_template": None,
            "polyedge": False,
        },
    ),
    "Pan4969": {  # TSO500 no UTRs. TERT promoter
        "panel_name": "tso500_low_throughput",
        "pipeline": "TSO500",
        "capture_type": "Hybridisation",
        "sambamba_bedfile": "Pan4969dataSambamba.bed",
        "clinical_coverage_depth": 100,
        "multiqc_coverage_level": 100,
        "coverage_min_basecall_qual": 25,
        "coverage_min_mapping_qual": 30,
        "congenica_project": False,
        "congenica_credentials": False,
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "variant_calling_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "hsmetrics_bedfile": None,
        "congenica_IR_template": None,
        "polyedge": False,
    },
    "Pan5085": {  # TSO500 High throughput Synnovis. no UTRs. TERT promoter
        "panel_name": "tso500_high_throughput",
        "pipeline": "TSO500",
        "capture_type": "Hybridisation",
        "sambamba_bedfile": "Pan4969dataSambamba.bed",
        "clinical_coverage_depth": 100,
        "multiqc_coverage_level": 100,
        "coverage_min_basecall_qual": 25,
        "coverage_min_mapping_qual": 30,
        "congenica_project": False,
        "congenica_credentials": False,
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "variant_calling_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "hsmetrics_bedfile": None,
        "congenica_IR_template": None,
        "polyedge": False,
    },
    "Pan5112": {  # TSO500 High throughput BSPS. no UTRs. TERT promoter
        "panel_name": "tso500_high_throughput",
        "pipeline": "TSO500",
        "capture_type": "Hybridisation",
        "sambamba_bedfile": "Pan4969dataSambamba.bed",
        "clinical_coverage_depth": 100,
        "multiqc_coverage_level": 100,
        "coverage_min_basecall_qual": 25,
        "coverage_min_mapping_qual": 30,
        "drylab_dnanexus_id": "BSPS_MD",
        "congenica_project": False,
        "congenica_credentials": False,
        "FH": False,
        "masked_reference": False,
        "variant_calling_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "hsmetrics_bedfile": None,
        "congenica_IR_template": None,
        "polyedge": False,
    },
    "Pan5114": {  # TSO500 High throughput Control. no UTRs. TERT promoter
        "panel_name": "tso500_high_throughput",
        "pipeline": "TSO500",
        "capture_type": "Hybridisation",
        "sambamba_bedfile": "Pan4969dataSambamba.bed",
        "clinical_coverage_depth": 100,
        "multiqc_coverage_level": 100,
        "coverage_min_basecall_qual": 25,
        "coverage_min_mapping_qual": 30,
        "drylab_dnanexus_id": "BSPS_MD",
        "congenica_project": False,
        "congenica_credentials": False,
        "FH": False,
        "masked_reference": False,
        "variant_calling_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "hsmetrics_bedfile": None,
        "congenica_IR_template": None,
        "polyedge": False,
    },
    "Pan4579": {  # VCP2 M1.1 - Somatic
        "panel_name": "vcp2_somatic",
        "pipeline": "mokacan",
        "capture_type": "Hybridisation",
        "multiqc_coverage_level": 30,
        "variant_calling_bedfile": "Pan4578data.bed",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "clinical_coverage_depth": 200,
        "congenica_project": False,
        "congenica_credentials": False,
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "sambamba_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4574": {  # VCP2 M1.2 - Somatic
        "panel_name": "vcp2_somatic",
        "pipeline": "mokacan",
        "capture_type": "Hybridisation",
        "multiqc_coverage_level": 30,
        "variant_calling_bedfile": "Pan4577data.bed",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "clinical_coverage_depth": 200,
        "congenica_project": False,
        "congenica_credentials": False,
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "sambamba_bedfile": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4119": {  # VCP1 R134 - FH small panel (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4664",
        "analyse_RPKM": True,
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "FH": True,
        "congenica_credentials": "Viapath",
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4121": {  # VCP1 R184 - CF (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4862",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4122": {  # VCP1 R25 - FGFR (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "5291",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4125": {  # VCP1 R73 - DMD (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4861",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4126": {  # VCP1 R337 - CADASIL (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4865",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4974": {  # VCP1 R112 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4975": {  # VCP1 R115 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4976": {  # VCP1 R116 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4977": {  # VCP1 R117 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4978": {  # VCP1 R118 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4979": {  # VCP1 R119 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4980": {  # VCP1 R120 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4981": {  # VCP1 R121 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4982": {  # VCP1 R122 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4983": {  # VCP1 R123 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4984": {  # VCP1 R124 - Molecular Haemostasis (Viapath)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4145": {  # VCP3 R79 - CMD (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "4666",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4146": {  # VCP3 R81 - CM (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "4666",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4149": {  # VCP2 BRCA (Viapath)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_project": "4665",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4150": {  # VCP2 R207 - ovarian cancer (Viapath)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_project": "4864",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": "MSH2",
    },
    "Pan4127": {  # VCP2 R209 - colorectal cancer (Viapath)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_project": "5093",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4129": {  # VCP2 R210 - Lynch syndrome (Viapath)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_project": "5094",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": "MSH2",
    },
    "Pan4964": {  # VCP2 R259 - nijmegen breakage (Viapath)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_project": "9118",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4130": {  # VCP2 R211 - polyposis (Viapath)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_project": "5095",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": "MSH2",
    },
    "Pan4132": {  # VCP3 R56 (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "5092",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4134": {  # VCP3 R57 (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "5092",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4136": {  # VCP3 R58 (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "5092",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4137": {  # VCP3 R60 (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "5092",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4138": {  # VCP3 R62 (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "5092",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4143": {  # VCP3 R66 (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "5092",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4144": {  # VCP3 R78 (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "5092",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4151": {  # VCP3 R82 - limb girdle (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "5092",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4314": {  # VCP3 R229 (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "5290",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4351": {  # VCP3 R227 (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "5522",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4387": {  # VCP3 R90 - Bleeding and platelet disorders (Viapath)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    # VCP3 R97 - Thrombophilia with a likely monogenic cause (Viapath)
    "Pan4390": {
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4362",
        "congenica_project": "4699",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "congenica_IR_template": "priority",
        "polyedge": False,
    },
    "Pan4821": {  # VCP1 R13 - FH (STG)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4203",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": True,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4822": {  # VCP1 R184 - CF (STG)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4203",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4823": {  # VCP1 R25_ - FGFR (STG)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4203",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4824": {  # VCP1 R73 - DMD (STG)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4203",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4825": {  # VCP1 R337 - cadasil (STG)
        "panel_name": "vcp1",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan4399",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4203",
        "hsmetrics_bedfile": "Pan4397data.bed",
        "variant_calling_bedfile": "Pan4398data.bed",
        "sambamba_bedfile": "Pan4397dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4816": {  # VCP2 R208 - BRCA (STG)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "1099",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4817": {  # VCP2 R207 - ovarian (STG)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "1099",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": "MSH2",
    },
    "Pan4818": {  # VCP2 R209 - colorectal (STG)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4202",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4819": {  # VCP2 R210 - lynch (STG)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4202",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": "MSH2",
    },
    "Pan4820": {  # VCP2 R211 - polyposis (STG)
        "panel_name": "vcp2",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3614",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4202",
        "hsmetrics_bedfile": "Pan4949data.bed",
        "variant_calling_bedfile": "Pan4948data.bed",
        "sambamba_bedfile": "Pan4949dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": "MSH2",
    },
    "Pan4826": {  # VCP3 R56 - (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4827": {  # VCP3 R57 - (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4828": {  # VCP3 R58 - (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4829": {  # VCP3 R60 - (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4830": {  # VCP3 R62 - (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4831": {  # VCP3 R66 - (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4832": {  # VCP3 R78 - (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4833": {  # VCP3 R79 - CMD (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4834": {  # VCP3 R81 - CM (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4835": {  # VCP3 R82 - limb girdle (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan4836": {  # VCP3 R229 - (STG)
        "panel_name": "vcp3",
        "pipeline": "mokapipe",
        "capture_type": "Hybridisation",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "RPKM_bedfile_pan_number": "Pan3974",
        "congenica_credentials": "STG",
        "congenica_IR_template": "non-priority",
        "congenica_project": "4201",
        "hsmetrics_bedfile": "Pan4995data.bed",
        "variant_calling_bedfile": "Pan4995data.bed",
        "sambamba_bedfile": "Pan4995dataSambamba.bed",
        "FH": False,
        "drylab_dnanexus_id": None,
        "masked_reference": False,
        "peddy": False,
        "polyedge": False,
    },
    "Pan5007": {  # LRPCR R207 - PMS2 (Viapath)
        "panel_name": "lrpcr",
        "pipeline": "mokapipe",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "capture_type": "Amplicon",
        "congenica_IR_template": "priority",
        "congenica_project": "9986",
        "hsmetrics_bedfile": "Pan4967_reference.bed",  # LRPCR amplicon BEDfile
        "variant_calling_bedfile": "Pan4767data.bed",
        "sambamba_bedfile": "Pan5018dataSambamba.bed",
        "masked_reference": MASKED_REFERENCE,
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "polyedge": False,
    },
    "Pan5008": {  # LRPCR R207 - PMS2 (STG)
        "panel_name": "lrpcr",
        "pipeline": "mokapipe",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "capture_type": "Amplicon",
        "congenica_IR_template": "non-priority",
        "congenica_project": "10010",
        "congenica_credentials": "STG",
        "hsmetrics_bedfile": "Pan4967_reference.bed",  # LRPCR amplicon BEDfile
        "variant_calling_bedfile": "Pan4767data.bed",
        "sambamba_bedfile": "Pan5018dataSambamba.bed",
        "masked_reference": MASKED_REFERENCE,
        "FH": False,
        "drylab_dnanexus_id": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "polyedge": False,
    },
    "Pan5009": {  # LRPCR R208 - CHEK2 (Viapath)
        "panel_name": "lrpcr",
        "pipeline": "mokapipe",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "capture_type": "Amplicon",
        "congenica_IR_template": "priority",
        "congenica_project": "9984",
        "hsmetrics_bedfile": "Pan4967_reference.bed",  # LRPCR amplicon BEDfile
        "variant_calling_bedfile": "Pan4767data.bed",
        "sambamba_bedfile": "Pan5018dataSambamba.bed",
        "masked_reference": MASKED_REFERENCE,
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "polyedge": False,
    },
    "Pan5010": {  # LRPCR R208 - CHEK2 (STG)
        "panel_name": "lrpcr",
        "pipeline": "mokapipe",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "capture_type": "Amplicon",
        "congenica_IR_template": "non-priority",
        "congenica_project": "10009",
        "congenica_credentials": "STG",
        "hsmetrics_bedfile": "Pan4967_reference.bed",  # LRPCR amplicon BEDfile
        "variant_calling_bedfile": "Pan4766data.bed",
        "sambamba_bedfile": "Pan5018dataSambamba.bed",
        "masked_reference": MASKED_REFERENCE,
        "FH": False,
        "drylab_dnanexus_id": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "polyedge": False,
    },
    "Pan5011": {  # LRPCR R210 - PMS2 (Viapath)
        "panel_name": "lrpcr",
        "pipeline": "mokapipe",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "capture_type": "Amplicon",
        "congenica_IR_template": "priority",
        "congenica_project": "9981",
        "hsmetrics_bedfile": "Pan4967_reference.bed",  # LRPCR amplicon BEDfile
        "variant_calling_bedfile": "Pan4767data.bed",
        "sambamba_bedfile": "Pan5018dataSambamba.bed",
        "masked_reference": MASKED_REFERENCE,
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "polyedge": False,
    },
    "Pan5012": {  # LRPCR R210 - PMS2 (STG)
        "panel_name": "lrpcr",
        "pipeline": "mokapipe",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "capture_type": "Amplicon",
        "congenica_IR_template": "non-priority",
        "congenica_project": "10042",
        "congenica_credentials": "STG",
        "hsmetrics_bedfile": "Pan4967_reference.bed",  # LRPCR amplicon BEDfile
        "variant_calling_bedfile": "Pan4767data.bed",
        "sambamba_bedfile": "Pan5018dataSambamba.bed",
        "masked_reference": MASKED_REFERENCE,
        "FH": False,
        "drylab_dnanexus_id": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "polyedge": False,
    },
    "Pan5013": {  # LRPCR R211 - PMS2 (Viapath)
        "panel_name": "lrpcr",
        "pipeline": "mokapipe",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "capture_type": "Amplicon",
        "congenica_IR_template": "priority",
        "congenica_project": "9982",
        "hsmetrics_bedfile": "Pan4967_reference.bed",  # LRPCR amplicon BEDfile
        "variant_calling_bedfile": "Pan4767data.bed",
        "sambamba_bedfile": "Pan5018dataSambamba.bed",
        "masked_reference": MASKED_REFERENCE,
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "polyedge": False,
    },
    "Pan5014": {  # LRPCR R211 - PMS2 (STG)
        "panel_name": "lrpcr",
        "pipeline": "mokapipe",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "capture_type": "Amplicon",
        "congenica_IR_template": "non-priority",
        "congenica_project": "10042",
        "congenica_credentials": "STG",
        "hsmetrics_bedfile": "Pan4967_reference.bed",  # LRPCR amplicon BEDfile
        "variant_calling_bedfile": "Pan4767data.bed",
        "sambamba_bedfile": "Pan5018dataSambamba.bed",
        "masked_reference": MASKED_REFERENCE,
        "FH": False,
        "drylab_dnanexus_id": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "polyedge": False,
    },
    "Pan5015": {  # LRPCR R71 - SMN1 (Viapath)
        "panel_name": "lrpcr",
        "pipeline": "mokapipe",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "capture_type": "Amplicon",
        "congenica_IR_template": "non-priority",
        "congenica_project": "9547",
        "hsmetrics_bedfile": "Pan4967_reference.bed",  # LRPCR amplicon BEDfile
        "variant_calling_bedfile": "Pan4971data.bed",
        "sambamba_bedfile": "Pan5018dataSambamba.bed",
        "masked_reference": MASKED_REFERENCE,
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "polyedge": False,
    },
    "Pan5016": {  # LRPCR R239 - IKBKG (Viapath)
        "panel_name": "lrpcr",
        "pipeline": "mokapipe",
        "clinical_coverage_depth": False,
        "multiqc_coverage_level": 30,
        "capture_type": "Amplicon",
        "congenica_IR_template": "priority",
        "congenica_project": "9985",
        "hsmetrics_bedfile": "Pan4967_reference.bed",  # LRPCR amplicon BEDfile
        "variant_calling_bedfile": "Pan4768data.bed",
        "sambamba_bedfile": "Pan5018dataSambamba.bed",
        "masked_reference": MASKED_REFERENCE,
        "congenica_credentials": "Viapath",
        "FH": False,
        "drylab_dnanexus_id": None,
        "RPKM_bedfile_pan_number": None,
        "peddy": False,
        "polyedge": False,
    },
}

# Extract pan number lists from panel dict
# vcp1_panel_list, vcp2_panel_list and vcp3_panel_list are also used by the
# trend analysis script

# List of all panel numbers from PANEL_DICT
PANEL_LIST = list(PANEL_DICT.keys())
# Per-capture panel numbers for use with RPKM
VCP1_PANEL_LIST = [
    k for k, v in PANEL_DICT.items() if PANEL_DICT[k]["panel_name"] == "vcp1"
]
VCP2_PANEL_LIST = [
    k for k, v in PANEL_DICT.items() if PANEL_DICT[k]["panel_name"] == "vcp2"
]
VCP3_PANEL_LIST = [
    k for k, v in PANEL_DICT.items() if PANEL_DICT[k]["panel_name"] == "vcp3"
]
TSO500_PANEL_LIST = [
    k for k, v in PANEL_DICT.items() if PANEL_DICT[k]["pipeline"] == "TSO500"
]
WES_PANEL_LIST = [
    k for k, v in PANEL_DICT.items() if PANEL_DICT[k]["pipeline"] == "mokawes"
]
SNP_PANEL_LIST = [
    k for k, v in PANEL_DICT.items() if PANEL_DICT[k]["pipeline"] == "mokasnp"
]
ARCHER_PANEL_LIST = [
    k for k, v in PANEL_DICT.items() if PANEL_DICT[k]["pipeline"] == "archerdx"
]
SWIFT_57G_PANEL_LIST = [
    k
    for k, v in PANEL_DICT.items()
    if PANEL_DICT[k]["panel_name"] == "swift_57g"
]
SWIFT_EGFR_PANEL_LIST = [
    k
    for k, v in PANEL_DICT.items()
    if PANEL_DICT[k]["panel_name"] == "swift_egfr"
]
MOKACAN_PANEL_LIST = [
    k for k, v in PANEL_DICT.items() if PANEL_DICT[k]["pipeline"] == "mokacan"
]
LRPCR_PANEL_LIST = [
    k for k, v in PANEL_DICT.items() if PANEL_DICT[k]["panel_name"] == "lrpcr"
]
