name: Automated scripts

on:
  push:
    branches:
      - master
      - 'feature/**'
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10.6']

    steps:
      - name: Checkout head
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          run: git checkout HEAD^
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install flake8==6.0.0 wheel==0.38.4 pytest==7.2.1
          pip3 install -r requirements.txt
          echo "dummytoken" > /home/runner/work/.dnanexus_auth_token
          echo "dummypw" > /home/runner/work/.amazon_email_pw
          echo "dummyuser" > /home/runner/work/.amazon_email_username
      - name: Lint with flake8
        run: |
          # stop the build if there are:
          # - syntax errors (E9)
          # - common assertion and comparison gotchas (F63)
          # - control flow gotchas (F7)
          # - undefined names (F82)
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
      - name: Test with pytest
      # We do not want it to run the email tests because the credentials are not stored in GitHub
        run: |
          python3 -m pytest -k 'not email'
      # TODO can the bcl2fastq tests be included if the docker image is pulled as part of the tests, or included in the repo as a tar?
